# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BillInquiryTelecom.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'BillInquiryTelecom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x42illInquiryTelecom.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"f\n\x12\x42illInquiryTelecom\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x15\n\rprovince_code\x18\x02 \x01(\r\x12\x18\n\x10telephone_number\x18\x03 \x01(\x04\"\x9a\x02\n\x1a\x42illInquiryTelecomResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\x12<\n\x08mid_term\x18\x04 \x01(\x0b\x32*.proto.BillInquiryTelecomResponse.BillInfo\x12=\n\tlast_term\x18\x05 \x01(\x0b\x32*.proto.BillInquiryTelecomResponse.BillInfo\x1a;\n\x08\x42illInfo\x12\x0f\n\x07\x62ill_id\x18\x01 \x01(\x04\x12\x0e\n\x06pay_id\x18\x02 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x42)\n\x0enet.iGap.protoB\x17ProtoBillInquiryTelecomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BillInquiryTelecom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\027ProtoBillInquiryTelecom'
  _globals['_BILLINQUIRYTELECOM']._serialized_start=66
  _globals['_BILLINQUIRYTELECOM']._serialized_end=168
  _globals['_BILLINQUIRYTELECOMRESPONSE']._serialized_start=171
  _globals['_BILLINQUIRYTELECOMRESPONSE']._serialized_end=453
  _globals['_BILLINQUIRYTELECOMRESPONSE_BILLINFO']._serialized_start=394
  _globals['_BILLINQUIRYTELECOMRESPONSE_BILLINFO']._serialized_end=453
# @@protoc_insertion_point(module_scope)
