# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BillInquiryMci.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'BillInquiryMci.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42illInquiryMci.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"H\n\x0e\x42illInquiryMci\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x15\n\rmobile_number\x18\x02 \x01(\x04\"\xaf\x02\n\x16\x42illInquiryMciResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x38\n\x08mid_term\x18\x04 \x01(\x0b\x32&.proto.BillInquiryMciResponse.BillInfo\x12\x39\n\tlast_term\x18\x05 \x01(\x0b\x32&.proto.BillInquiryMciResponse.BillInfo\x1a\\\n\x08\x42illInfo\x12\x0e\n\x06status\x18\x01 \x01(\r\x12\x0f\n\x07\x62ill_id\x18\x02 \x01(\x04\x12\x0e\n\x06pay_id\x18\x03 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x04\x12\x0f\n\x07message\x18\x05 \x01(\tB%\n\x0enet.iGap.protoB\x13ProtoBillInquiryMcib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BillInquiryMci_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\023ProtoBillInquiryMci'
  _globals['_BILLINQUIRYMCI']._serialized_start=62
  _globals['_BILLINQUIRYMCI']._serialized_end=134
  _globals['_BILLINQUIRYMCIRESPONSE']._serialized_start=137
  _globals['_BILLINQUIRYMCIRESPONSE']._serialized_end=440
  _globals['_BILLINQUIRYMCIRESPONSE_BILLINFO']._serialized_start=348
  _globals['_BILLINQUIRYMCIRESPONSE_BILLINFO']._serialized_end=440
# @@protoc_insertion_point(module_scope)
