# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChannelCheckUsername.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ChannelCheckUsername.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43hannelCheckUsername.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"Z\n\x14\x43hannelCheckUsername\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\x04\"\xcc\x01\n\x1c\x43hannelCheckUsernameResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.proto.ChannelCheckUsernameResponse.Status\"M\n\x06Status\x12\x0b\n\x07INVALID\x10\x00\x12\t\n\x05TAKEN\x10\x01\x12\r\n\tAVAILABLE\x10\x02\x12\x1c\n\x18OCCUPYING_LIMIT_EXCEEDED\x10\x03\x42+\n\x0enet.iGap.protoB\x19ProtoChannelCheckUsernameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelCheckUsername_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\031ProtoChannelCheckUsername'
  _globals['_CHANNELCHECKUSERNAME']._serialized_start=68
  _globals['_CHANNELCHECKUSERNAME']._serialized_end=158
  _globals['_CHANNELCHECKUSERNAMERESPONSE']._serialized_start=161
  _globals['_CHANNELCHECKUSERNAMERESPONSE']._serialized_end=365
  _globals['_CHANNELCHECKUSERNAMERESPONSE_STATUS']._serialized_start=288
  _globals['_CHANNELCHECKUSERNAMERESPONSE_STATUS']._serialized_end=365
# @@protoc_insertion_point(module_scope)
