# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatSendMessage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ChatSendMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43hatSendMessage.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\xfc\x02\n\x0f\x43hatSendMessage\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12,\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x16.proto.RoomMessageType\x12\x0f\n\x07room_id\x18\x03 \x01(\x04\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x12\n\nattachment\x18\x05 \x01(\t\x12,\n\x08location\x18\x06 \x01(\x0b\x32\x1a.proto.RoomMessageLocation\x12*\n\x07\x63ontact\x18\x07 \x01(\x0b\x32\x19.proto.RoomMessageContact\x12\x10\n\x08reply_to\x18\x08 \x01(\x04\x12\x33\n\x0c\x66orward_from\x18\t \x01(\x0b\x32\x1d.proto.RoomMessageForwardFrom\x12\x11\n\trandom_id\x18\n \x01(\x04\x12\x17\n\x0f\x61\x64\x64itional_type\x18\x0b \x01(\r\x12\x17\n\x0f\x61\x64\x64itional_data\x18\x0c \x01(\t\"w\n\x17\x43hatSendMessageResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12(\n\x0croom_message\x18\x03 \x01(\x0b\x32\x12.proto.RoomMessageB&\n\x0enet.iGap.protoB\x14ProtoChatSendMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatSendMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\024ProtoChatSendMessage'
  _globals['_CHATSENDMESSAGE']._serialized_start=78
  _globals['_CHATSENDMESSAGE']._serialized_end=458
  _globals['_CHATSENDMESSAGERESPONSE']._serialized_start=460
  _globals['_CHATSENDMESSAGERESPONSE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
