# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientCondition.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientCondition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x43lientCondition.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xbc\x05\n\x0f\x43lientCondition\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12*\n\x05rooms\x18\x02 \x03(\x0b\x32\x1b.proto.ClientCondition.Room\x1a\xdb\x04\n\x04Room\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x17\n\x0fmessage_version\x18\x03 \x01(\x04\x12\x16\n\x0estatus_version\x18\x04 \x01(\x04\x12\x16\n\x0e\x64\x65lete_version\x18\x05 \x01(\x04\x12\"\n\x1aoffline_deleted_deprecated\x18\x06 \x03(\x04\x12\x41\n\x0eoffline_edited\x18\x07 \x03(\x0b\x32).proto.ClientCondition.Room.OfflineEdited\x12\x14\n\x0coffline_seen\x18\x08 \x03(\x04\x12\x10\n\x08\x63lear_id\x18\t \x01(\x04\x12\x16\n\x0e\x63\x61\x63he_start_id\x18\n \x01(\x04\x12\x14\n\x0c\x63\x61\x63he_end_id\x18\x0b \x01(\x04\x12=\n\x0coffline_mute\x18\x0c \x01(\x0e\x32\'.proto.ClientCondition.Room.OfflineMute\x12\x18\n\x10offline_listened\x18\r \x03(\x04\x12\x43\n\x0foffline_deleted\x18\x0e \x03(\x0b\x32*.proto.ClientCondition.Room.OfflineDeleted\x1a\x34\n\rOfflineEdited\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\x0f\n\x07message\x18\x02 \x01(\t\x1a\x32\n\x0eOfflineDeleted\x12\x12\n\nmessage_id\x18\x01 \x01(\x04\x12\x0c\n\x04\x62oth\x18\x04 \x01(\x08\"4\n\x0bOfflineMute\x12\r\n\tUNCHANGED\x10\x00\x12\t\n\x05MUTED\x10\x01\x12\x0b\n\x07UNMUTED\x10\x02\"<\n\x17\x43lientConditionResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.ResponseB&\n\x0enet.iGap.protoB\x14ProtoClientConditionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientCondition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\024ProtoClientCondition'
  _globals['_CLIENTCONDITION']._serialized_start=64
  _globals['_CLIENTCONDITION']._serialized_end=764
  _globals['_CLIENTCONDITION_ROOM']._serialized_start=161
  _globals['_CLIENTCONDITION_ROOM']._serialized_end=764
  _globals['_CLIENTCONDITION_ROOM_OFFLINEEDITED']._serialized_start=606
  _globals['_CLIENTCONDITION_ROOM_OFFLINEEDITED']._serialized_end=658
  _globals['_CLIENTCONDITION_ROOM_OFFLINEDELETED']._serialized_start=660
  _globals['_CLIENTCONDITION_ROOM_OFFLINEDELETED']._serialized_end=710
  _globals['_CLIENTCONDITION_ROOM_OFFLINEMUTE']._serialized_start=712
  _globals['_CLIENTCONDITION_ROOM_OFFLINEMUTE']._serialized_end=764
  _globals['_CLIENTCONDITIONRESPONSE']._serialized_start=766
  _globals['_CLIENTCONDITIONRESPONSE']._serialized_end=826
# @@protoc_insertion_point(module_scope)
