# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientJoinByUsername.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientJoinByUsername.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43lientJoinByUsername.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"I\n\x14\x43lientJoinByUsername\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x10\n\x08username\x18\x02 \x01(\t\"A\n\x1c\x43lientJoinByUsernameResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.ResponseB+\n\x0enet.iGap.protoB\x19ProtoClientJoinByUsernameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientJoinByUsername_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\031ProtoClientJoinByUsername'
  _globals['_CLIENTJOINBYUSERNAME']._serialized_start=68
  _globals['_CLIENTJOINBYUSERNAME']._serialized_end=141
  _globals['_CLIENTJOINBYUSERNAMERESPONSE']._serialized_start=143
  _globals['_CLIENTJOINBYUSERNAMERESPONSE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
