# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientUnsubscribeFromRoom.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientUnsubscribeFromRoom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x43lientUnsubscribeFromRoom.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"M\n\x19\x43lientUnsubscribeFromRoom\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\"F\n!ClientUnsubscribeFromRoomResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.ResponseB0\n\x0enet.iGap.protoB\x1eProtoClientUnsubscribeFromRoomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientUnsubscribeFromRoom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\036ProtoClientUnsubscribeFromRoom'
  _globals['_CLIENTUNSUBSCRIBEFROMROOM']._serialized_start=73
  _globals['_CLIENTUNSUBSCRIBEFROMROOM']._serialized_end=150
  _globals['_CLIENTUNSUBSCRIBEFROMROOMRESPONSE']._serialized_start=152
  _globals['_CLIENTUNSUBSCRIBEFROMROOMRESPONSE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
