# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientSearchRoomHistory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientSearchRoomHistory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x43lientSearchRoomHistory.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\xff\x01\n\x17\x43lientSearchRoomHistory\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x0e\n\x06offset\x18\x03 \x01(\r\x12\x35\n\x06\x66ilter\x18\x04 \x01(\x0e\x32%.proto.ClientSearchRoomHistory.Filter\x12\x19\n\x11offset_message_id\x18\x05 \x01(\x04\"P\n\x06\x46ilter\x12\t\n\x05IMAGE\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\t\n\x05VOICE\x10\x03\x12\x07\n\x03GIF\x10\x04\x12\x08\n\x04\x46ILE\x10\x05\x12\x07\n\x03URL\x10\x06\"\x95\x01\n\x1f\x43lientSearchRoomHistoryResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x12\n\ntotalCount\x18\x02 \x01(\r\x12\x17\n\x0fnotDeletedCount\x18\x03 \x01(\r\x12\"\n\x06result\x18\x04 \x03(\x0b\x32\x12.proto.RoomMessageB.\n\x0enet.iGap.protoB\x1cProtoClientSearchRoomHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientSearchRoomHistory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\034ProtoClientSearchRoomHistory'
  _globals['_CLIENTSEARCHROOMHISTORY']._serialized_start=86
  _globals['_CLIENTSEARCHROOMHISTORY']._serialized_end=341
  _globals['_CLIENTSEARCHROOMHISTORY_FILTER']._serialized_start=261
  _globals['_CLIENTSEARCHROOMHISTORY_FILTER']._serialized_end=341
  _globals['_CLIENTSEARCHROOMHISTORYRESPONSE']._serialized_start=344
  _globals['_CLIENTSEARCHROOMHISTORYRESPONSE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
