# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientCountRoomHistory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientCountRoomHistory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43lientCountRoomHistory.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"J\n\x16\x43lientCountRoomHistory\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\"\xb6\x01\n\x1e\x43lientCountRoomHistoryResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\r\n\x05media\x18\x02 \x01(\r\x12\r\n\x05image\x18\x03 \x01(\r\x12\r\n\x05video\x18\x04 \x01(\r\x12\r\n\x05\x61udio\x18\x05 \x01(\r\x12\r\n\x05voice\x18\x06 \x01(\r\x12\x0b\n\x03gif\x18\x07 \x01(\r\x12\x0c\n\x04\x66ile\x18\x08 \x01(\r\x12\x0b\n\x03url\x18\t \x01(\rB-\n\x0enet.iGap.protoB\x1bProtoClientCountRoomHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientCountRoomHistory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\033ProtoClientCountRoomHistory'
  _globals['_CLIENTCOUNTROOMHISTORY']._serialized_start=70
  _globals['_CLIENTCOUNTROOMHISTORY']._serialized_end=144
  _globals['_CLIENTCOUNTROOMHISTORYRESPONSE']._serialized_start=147
  _globals['_CLIENTCOUNTROOMHISTORYRESPONSE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
