# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientGetPromote.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientGetPromote.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43lientGetPromote.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"3\n\x10\x43lientGetPromote\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xed\x01\n\x18\x43lientGetPromoteResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x38\n\x07promote\x18\x02 \x03(\x0b\x32\'.proto.ClientGetPromoteResponse.Promote\x1at\n\x07Promote\x12:\n\x04type\x18\x01 \x01(\x0e\x32,.proto.ClientGetPromoteResponse.Promote.Type\x12\n\n\x02id\x18\x02 \x01(\x04\"!\n\x04Type\x12\x08\n\x04USER\x10\x00\x12\x0f\n\x0bPUBLIC_ROOM\x10\x01\x42\'\n\x0enet.iGap.protoB\x15ProtoClientGetPromoteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientGetPromote_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\025ProtoClientGetPromote'
  _globals['_CLIENTGETPROMOTE']._serialized_start=64
  _globals['_CLIENTGETPROMOTE']._serialized_end=115
  _globals['_CLIENTGETPROMOTERESPONSE']._serialized_start=118
  _globals['_CLIENTGETPROMOTERESPONSE']._serialized_end=355
  _globals['_CLIENTGETPROMOTERESPONSE_PROMOTE']._serialized_start=239
  _globals['_CLIENTGETPROMOTERESPONSE_PROMOTE']._serialized_end=355
  _globals['_CLIENTGETPROMOTERESPONSE_PROMOTE_TYPE']._serialized_start=322
  _globals['_CLIENTGETPROMOTERESPONSE_PROMOTE_TYPE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
