# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ClientGetRoomHistory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ClientGetRoomHistory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43lientGetRoomHistory.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\xca\x01\n\x14\x43lientGetRoomHistory\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x18\n\x10\x66irst_message_id\x18\x03 \x01(\x04\x12\x38\n\tdirection\x18\x04 \x01(\x0e\x32%.proto.ClientGetRoomHistory.Direction\x12\r\n\x05limit\x18\x05 \x01(\r\"\x1d\n\tDirection\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\"f\n\x1c\x43lientGetRoomHistoryResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12#\n\x07message\x18\x02 \x03(\x0b\x32\x12.proto.RoomMessageB+\n\x0enet.iGap.protoB\x19ProtoClientGetRoomHistoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientGetRoomHistory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\031ProtoClientGetRoomHistory'
  _globals['_CLIENTGETROOMHISTORY']._serialized_start=83
  _globals['_CLIENTGETROOMHISTORY']._serialized_end=285
  _globals['_CLIENTGETROOMHISTORY_DIRECTION']._serialized_start=256
  _globals['_CLIENTGETROOMHISTORY_DIRECTION']._serialized_end=285
  _globals['_CLIENTGETROOMHISTORYRESPONSE']._serialized_start=287
  _globals['_CLIENTGETROOMHISTORYRESPONSE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
