# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ConnectionSecuring.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ConnectionSecuring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43onnectionSecuring.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xc6\x01\n\x1a\x43onnectionSecuringResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x12\n\npublic_key\x18\x02 \x01(\t\x12\x1c\n\x14symmetric_key_length\x18\x03 \x01(\r\x12\x1a\n\x12heartbeat_interval\x18\x04 \x01(\r\x12\x19\n\x11primary_node_name\x18\x05 \x01(\t\x12\x1c\n\x14secondary_chunk_size\x18\x06 \x01(\r\"a\n\x16\x43onnectionSymmetricKey\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x15\n\rsymmetric_key\x18\x02 \x01(\x0c\x12\x0f\n\x07version\x18\x03 \x01(\r\"\xf4\x01\n\x1e\x43onnectionSymmetricKeyResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12<\n\x06status\x18\x02 \x01(\x0e\x32,.proto.ConnectionSymmetricKeyResponse.Status\x12\x18\n\x10symmetric_method\x18\x03 \x01(\t\x12\x19\n\x11symmetric_iv_size\x18\x04 \x01(\r\x12\x16\n\x0esecurity_issue\x18\x05 \x01(\x08\"$\n\x06Status\x12\x0c\n\x08REJECTED\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\x42)\n\x0enet.iGap.protoB\x17ProtoConnectionSecuringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConnectionSecuring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\027ProtoConnectionSecuring'
  _globals['_CONNECTIONSECURINGRESPONSE']._serialized_start=67
  _globals['_CONNECTIONSECURINGRESPONSE']._serialized_end=265
  _globals['_CONNECTIONSYMMETRICKEY']._serialized_start=267
  _globals['_CONNECTIONSYMMETRICKEY']._serialized_end=364
  _globals['_CONNECTIONSYMMETRICKEYRESPONSE']._serialized_start=367
  _globals['_CONNECTIONSYMMETRICKEYRESPONSE']._serialized_end=611
  _globals['_CONNECTIONSYMMETRICKEYRESPONSE_STATUS']._serialized_start=575
  _globals['_CONNECTIONSYMMETRICKEYRESPONSE_STATUS']._serialized_end=611
# @@protoc_insertion_point(module_scope)
