# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Error.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'Error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x45rror.proto\x12\x05proto\x1a\x0eResponse.proto\"y\n\rErrorResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x12\n\nmajor_code\x18\x02 \x01(\r\x12\x12\n\nminor_code\x18\x03 \x01(\r\x12\x0c\n\x04wait\x18\x04 \x01(\r\x12\x0f\n\x07message\x18\x05 \x01(\tB\x1c\n\x0enet.iGap.protoB\nProtoErrorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\nProtoError'
  _globals['_ERRORRESPONSE']._serialized_start=38
  _globals['_ERRORRESPONSE']._serialized_end=159
# @@protoc_insertion_point(module_scope)
