# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FileDownload.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'FileDownload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46ileDownload.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xe9\x01\n\x0c\x46ileDownload\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x12\x11\n\tmax_limit\x18\x04 \x01(\x05\x12.\n\x08selector\x18\x05 \x01(\x0e\x32\x1c.proto.FileDownload.Selector\"V\n\x08Selector\x12\x08\n\x04\x46ILE\x10\x00\x12\x13\n\x0fSMALL_THUMBNAIL\x10\x01\x12\x13\n\x0fLARGE_THUMBNAIL\x10\x02\x12\x16\n\x12WAVEFORM_THUMBNAIL\x10\x03\"H\n\x14\x46ileDownloadResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\r\n\x05\x62ytes\x18\x04 \x01(\x0c\x42#\n\x0enet.iGap.protoB\x11ProtoFileDownloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileDownload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\021ProtoFileDownload'
  _globals['_FILEDOWNLOAD']._serialized_start=61
  _globals['_FILEDOWNLOAD']._serialized_end=294
  _globals['_FILEDOWNLOAD_SELECTOR']._serialized_start=208
  _globals['_FILEDOWNLOAD_SELECTOR']._serialized_end=294
  _globals['_FILEDOWNLOADRESPONSE']._serialized_start=296
  _globals['_FILEDOWNLOADRESPONSE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
