# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FileUploadStatus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'FileUploadStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x46ileUploadStatus.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"B\n\x10\x46ileUploadStatus\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\r\n\x05token\x18\x02 \x01(\t\"\xe8\x01\n\x18\x46ileUploadStatusResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x36\n\x06status\x18\x02 \x01(\x0e\x32&.proto.FileUploadStatusResponse.Status\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x18\n\x10recheck_delay_ms\x18\x04 \x01(\r\"E\n\x06Status\x12\r\n\tUPLOADING\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\r\n\tPROCESSED\x10\x02\x12\r\n\tCORRUPTED\x10\x03\x42\'\n\x0enet.iGap.protoB\x15ProtoFileUploadStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileUploadStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\025ProtoFileUploadStatus'
  _globals['_FILEUPLOADSTATUS']._serialized_start=64
  _globals['_FILEUPLOADSTATUS']._serialized_end=130
  _globals['_FILEUPLOADSTATUSRESPONSE']._serialized_start=133
  _globals['_FILEUPLOADSTATUSRESPONSE']._serialized_end=365
  _globals['_FILEUPLOADSTATUSRESPONSE_STATUS']._serialized_start=296
  _globals['_FILEUPLOADSTATUSRESPONSE_STATUS']._serialized_end=365
# @@protoc_insertion_point(module_scope)
