# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FileUploadInit.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'FileUploadInit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x46ileUploadInit.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\x8e\x01\n\x0e\x46ileUploadInit\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x13\n\x0b\x66irst_bytes\x18\x02 \x01(\x0c\x12\x12\n\nlast_bytes\x18\x03 \x01(\x0c\x12\x0c\n\x04size\x18\x04 \x01(\x03\x12\x11\n\tfile_hash\x18\x05 \x01(\x0c\x12\x11\n\tfile_name\x18\x06 \x01(\t\"{\n\x16\x46ileUploadInitResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08progress\x18\x03 \x01(\x01\x12\x0e\n\x06offset\x18\x04 \x01(\x03\x12\r\n\x05limit\x18\x05 \x01(\x05\x42%\n\x0enet.iGap.protoB\x13ProtoFileUploadInitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileUploadInit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\023ProtoFileUploadInit'
  _globals['_FILEUPLOADINIT']._serialized_start=63
  _globals['_FILEUPLOADINIT']._serialized_end=205
  _globals['_FILEUPLOADINITRESPONSE']._serialized_start=207
  _globals['_FILEUPLOADINITRESPONSE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
