# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FileUpload.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'FileUpload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46ileUpload.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"[\n\nFileUpload\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x12\r\n\x05\x62ytes\x18\x04 \x01(\x0c\"r\n\x12\x46ileUploadResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x10\n\x08progress\x18\x02 \x01(\x01\x12\x13\n\x0bnext_offset\x18\x03 \x01(\x03\x12\x12\n\nnext_limit\x18\x04 \x01(\x05\x42!\n\x0enet.iGap.protoB\x0fProtoFileUploadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileUpload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\017ProtoFileUpload'
  _globals['_FILEUPLOAD']._serialized_start=58
  _globals['_FILEUPLOAD']._serialized_end=149
  _globals['_FILEUPLOADRESPONSE']._serialized_start=151
  _globals['_FILEUPLOADRESPONSE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
