# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GeoGetConfiguration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GeoGetConfiguration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19GeoGetConfiguration.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"6\n\x13GeoGetConfiguration\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xb6\x01\n\x1bGeoGetConfigurationResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x42\n\x0btile_server\x18\x02 \x03(\x0b\x32-.proto.GeoGetConfigurationResponse.TileServer\x12\x10\n\x08\x63\x61\x63he_id\x18\x03 \x01(\t\x1a\x1e\n\nTileServer\x12\x10\n\x08\x62\x61se_url\x18\x01 \x01(\tB*\n\x0enet.iGap.protoB\x18ProtoGeoGetConfigurationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GeoGetConfiguration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\030ProtoGeoGetConfiguration'
  _globals['_GEOGETCONFIGURATION']._serialized_start=67
  _globals['_GEOGETCONFIGURATION']._serialized_end=121
  _globals['_GEOGETCONFIGURATIONRESPONSE']._serialized_start=124
  _globals['_GEOGETCONFIGURATIONRESPONSE']._serialized_end=306
  _globals['_GEOGETCONFIGURATIONRESPONSE_TILESERVER']._serialized_start=276
  _globals['_GEOGETCONFIGURATIONRESPONSE_TILESERVER']._serialized_end=306
# @@protoc_insertion_point(module_scope)
