# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GeoGetNearbyCoordinate.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GeoGetNearbyCoordinate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cGeoGetNearbyCoordinate.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"S\n\x16GeoGetNearbyCoordinate\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\"\xcb\x01\n\x1eGeoGetNearbyCoordinateResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12<\n\x06result\x18\x02 \x03(\x0b\x32,.proto.GeoGetNearbyCoordinateResponse.Result\x1aH\n\x06Result\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bhas_comment\x18\x02 \x01(\x08\x12\x0b\n\x03lat\x18\x03 \x01(\x01\x12\x0b\n\x03lon\x18\x04 \x01(\x01\x42-\n\x0enet.iGap.protoB\x1bProtoGeoGetNearbyCoordinateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GeoGetNearbyCoordinate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\033ProtoGeoGetNearbyCoordinate'
  _globals['_GEOGETNEARBYCOORDINATE']._serialized_start=70
  _globals['_GEOGETNEARBYCOORDINATE']._serialized_end=153
  _globals['_GEOGETNEARBYCOORDINATERESPONSE']._serialized_start=156
  _globals['_GEOGETNEARBYCOORDINATERESPONSE']._serialized_end=359
  _globals['_GEOGETNEARBYCOORDINATERESPONSE_RESULT']._serialized_start=287
  _globals['_GEOGETNEARBYCOORDINATERESPONSE_RESULT']._serialized_end=359
# @@protoc_insertion_point(module_scope)
