# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GeoGetNearbyDistance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GeoGetNearbyDistance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aGeoGetNearbyDistance.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"Q\n\x14GeoGetNearbyDistance\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lon\x18\x03 \x01(\x01\"\xbf\x01\n\x1cGeoGetNearbyDistanceResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12:\n\x06result\x18\x02 \x03(\x0b\x32*.proto.GeoGetNearbyDistanceResponse.Result\x1a@\n\x06Result\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x13\n\x0bhas_comment\x18\x02 \x01(\x08\x12\x10\n\x08\x64istance\x18\x03 \x01(\rB+\n\x0enet.iGap.protoB\x19ProtoGeoGetNearbyDistanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GeoGetNearbyDistance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\031ProtoGeoGetNearbyDistance'
  _globals['_GEOGETNEARBYDISTANCE']._serialized_start=68
  _globals['_GEOGETNEARBYDISTANCE']._serialized_end=149
  _globals['_GEOGETNEARBYDISTANCERESPONSE']._serialized_start=152
  _globals['_GEOGETNEARBYDISTANCERESPONSE']._serialized_end=343
  _globals['_GEOGETNEARBYDISTANCERESPONSE_RESULT']._serialized_start=279
  _globals['_GEOGETNEARBYDISTANCERESPONSE_RESULT']._serialized_end=343
# @@protoc_insertion_point(module_scope)
