# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GroupGetMemberList.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GroupGetMemberList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GroupGetMemberList.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\xe5\x01\n\x12GroupGetMemberList\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x39\n\x0b\x66ilter_role\x18\x03 \x01(\x0e\x32$.proto.GroupGetMemberList.FilterRole\x12%\n\npagination\x18\x04 \x01(\x0b\x32\x11.proto.Pagination\";\n\nFilterRole\x12\x07\n\x03\x41LL\x10\x00\x12\n\n\x06MEMBER\x10\x01\x12\r\n\tMODERATOR\x10\x02\x12\t\n\x05\x41\x44MIN\x10\x03\"\xb8\x01\n\x1aGroupGetMemberListResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x38\n\x06member\x18\x02 \x03(\x0b\x32(.proto.GroupGetMemberListResponse.Member\x1a=\n\x06Member\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12#\n\x04role\x18\x02 \x01(\x0e\x32\x15.proto.GroupRoom.RoleB)\n\x0enet.iGap.protoB\x17ProtoGroupGetMemberListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupGetMemberList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\027ProtoGroupGetMemberList'
  _globals['_GROUPGETMEMBERLIST']._serialized_start=81
  _globals['_GROUPGETMEMBERLIST']._serialized_end=310
  _globals['_GROUPGETMEMBERLIST_FILTERROLE']._serialized_start=251
  _globals['_GROUPGETMEMBERLIST_FILTERROLE']._serialized_end=310
  _globals['_GROUPGETMEMBERLISTRESPONSE']._serialized_start=313
  _globals['_GROUPGETMEMBERLISTRESPONSE']._serialized_end=497
  _globals['_GROUPGETMEMBERLISTRESPONSE_MEMBER']._serialized_start=436
  _globals['_GROUPGETMEMBERLISTRESPONSE_MEMBER']._serialized_end=497
# @@protoc_insertion_point(module_scope)
