# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GroupUpdateStatus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GroupUpdateStatus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17GroupUpdateStatus.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\x83\x01\n\x11GroupUpdateStatus\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x12\n\nmessage_id\x18\x03 \x01(\x04\x12(\n\x06status\x18\x04 \x01(\x0e\x32\x18.proto.RoomMessageStatus\"\xc2\x01\n\x19GroupUpdateStatusResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0f\n\x07room_id\x18\x02 \x01(\x04\x12\x12\n\nmessage_id\x18\x03 \x01(\x04\x12(\n\x06status\x18\x04 \x01(\x0e\x32\x18.proto.RoomMessageStatus\x12\x16\n\x0estatus_version\x18\x05 \x01(\x04\x12\x1b\n\x13updater_author_hash\x18\x06 \x01(\tB(\n\x0enet.iGap.protoB\x16ProtoGroupUpdateStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupUpdateStatus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\026ProtoGroupUpdateStatus'
  _globals['_GROUPUPDATESTATUS']._serialized_start=80
  _globals['_GROUPUPDATESTATUS']._serialized_end=211
  _globals['_GROUPUPDATESTATUSRESPONSE']._serialized_start=214
  _globals['_GROUPUPDATESTATUSRESPONSE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
