# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GroupCheckUsername.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'GroupCheckUsername.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18GroupCheckUsername.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"X\n\x12GroupCheckUsername\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07room_id\x18\x03 \x01(\x04\"\xc8\x01\n\x1aGroupCheckUsernameResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x38\n\x06status\x18\x02 \x01(\x0e\x32(.proto.GroupCheckUsernameResponse.Status\"M\n\x06Status\x12\x0b\n\x07INVALID\x10\x00\x12\t\n\x05TAKEN\x10\x01\x12\r\n\tAVAILABLE\x10\x02\x12\x1c\n\x18OCCUPYING_LIMIT_EXCEEDED\x10\x03\x42)\n\x0enet.iGap.protoB\x17ProtoGroupCheckUsernameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GroupCheckUsername_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\027ProtoGroupCheckUsername'
  _globals['_GROUPCHECKUSERNAME']._serialized_start=66
  _globals['_GROUPCHECKUSERNAME']._serialized_end=154
  _globals['_GROUPCHECKUSERNAMERESPONSE']._serialized_start=157
  _globals['_GROUPCHECKUSERNAMERESPONSE']._serialized_end=357
  _globals['_GROUPCHECKUSERNAMERESPONSE_STATUS']._serialized_start=280
  _globals['_GROUPCHECKUSERNAMERESPONSE_STATUS']._serialized_end=357
# @@protoc_insertion_point(module_scope)
