# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InfoWallpaper.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'InfoWallpaper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13InfoWallpaper.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\x82\x01\n\rInfoWallpaper\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12%\n\x03\x66it\x18\x02 \x01(\x0e\x32\x18.proto.InfoWallpaper.Fit\")\n\x03\x46it\x12\t\n\x05PHONE\x10\x00\x12\n\n\x06TABLET\x10\x01\x12\x0b\n\x07\x44\x45SKTOP\x10\x02\"_\n\x15InfoWallpaperResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12#\n\twallpaper\x18\x02 \x03(\x0b\x32\x10.proto.WallpaperB$\n\x0enet.iGap.protoB\x12ProtoInfoWallpaperb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InfoWallpaper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\022ProtoInfoWallpaper'
  _globals['_INFOWALLPAPER']._serialized_start=76
  _globals['_INFOWALLPAPER']._serialized_end=206
  _globals['_INFOWALLPAPER_FIT']._serialized_start=165
  _globals['_INFOWALLPAPER_FIT']._serialized_end=206
  _globals['_INFOWALLPAPERRESPONSE']._serialized_start=208
  _globals['_INFOWALLPAPERRESPONSE']._serialized_end=303
# @@protoc_insertion_point(module_scope)
