# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: InfoLocation.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'InfoLocation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12InfoLocation.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"/\n\x0cInfoLocation\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\x8f\x01\n\x14InfoLocationResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x10\n\x08iso_code\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x61lling_code\x18\x03 \x01(\r\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07pattern\x18\x05 \x01(\t\x12\r\n\x05regex\x18\x06 \x01(\tB#\n\x0enet.iGap.protoB\x11ProtoInfoLocationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InfoLocation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\021ProtoInfoLocation'
  _globals['_INFOLOCATION']._serialized_start=60
  _globals['_INFOLOCATION']._serialized_end=107
  _globals['_INFOLOCATIONRESPONSE']._serialized_start=110
  _globals['_INFOLOCATIONRESPONSE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
