# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MplGetTopupToken.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'MplGetTopupToken.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16MplGetTopupToken.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xfe\x01\n\x10MplGetTopupToken\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x1c\n\x14\x63harge_mobile_number\x18\x02 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x04\x12*\n\x04type\x18\x04 \x01(\x0e\x32\x1c.proto.MplGetTopupToken.Type\"o\n\x04Type\x12\x14\n\x10IRANCELL_PREPAID\x10\x00\x12\x10\n\x0cIRANCELL_WOW\x10\x01\x12\x12\n\x0eIRANCELL_WIMAX\x10\x02\x12\x15\n\x11IRANCELL_POSTPAID\x10\x03\x12\x07\n\x03MCI\x10\x04\x12\x0b\n\x07RIGHTEL\x10\x05\"\x82\x01\n\x18MplGetTopupTokenResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\r\n\x05token\x18\x03 \x01(\t\x12\x13\n\x0b\x65xpire_time\x18\x04 \x01(\r\x12\x0f\n\x07message\x18\x05 \x01(\tB\'\n\x0enet.iGap.protoB\x15ProtoMplGetTopupTokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MplGetTopupToken_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\025ProtoMplGetTopupToken'
  _globals['_MPLGETTOPUPTOKEN']._serialized_start=65
  _globals['_MPLGETTOPUPTOKEN']._serialized_end=319
  _globals['_MPLGETTOPUPTOKEN_TYPE']._serialized_start=208
  _globals['_MPLGETTOPUPTOKEN_TYPE']._serialized_end=319
  _globals['_MPLGETTOPUPTOKENRESPONSE']._serialized_start=322
  _globals['_MPLGETTOPUPTOKENRESPONSE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
