# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PushRateSignaling.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'PushRateSignaling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PushRateSignaling.proto\x12\x05proto\x1a\x0eResponse.proto\"J\n\x19PushRateSignalingResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\n\n\x02id\x18\x02 \x01(\x04\x42(\n\x0enet.iGap.protoB\x16ProtoPushRateSignalingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PushRateSignaling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\026ProtoPushRateSignaling'
  _globals['_PUSHRATESIGNALINGRESPONSE']._serialized_start=50
  _globals['_PUSHRATESIGNALINGRESPONSE']._serialized_end=124
# @@protoc_insertion_point(module_scope)
