# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QrCodeJoin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'QrCodeJoin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10QrCodeJoin.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"C\n\nQrCodeJoin\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x14\n\x0cinvite_token\x18\x02 \x01(\t\"N\n\x12QrCodeJoinResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x15\n\rqr_code_image\x18\x02 \x01(\x0c\x42!\n\x0enet.iGap.protoB\x0fProtoQrCodeJoinb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QrCodeJoin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\017ProtoQrCodeJoin'
  _globals['_QRCODEJOIN']._serialized_start=58
  _globals['_QRCODEJOIN']._serialized_end=125
  _globals['_QRCODEJOINRESPONSE']._serialized_start=127
  _globals['_QRCODEJOINRESPONSE']._serialized_end=205
# @@protoc_insertion_point(module_scope)
