# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignalingGetLog.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'SignalingGetLog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2
import SignalingOffer_pb2 as SignalingOffer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SignalingGetLog.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\x1a\x14SignalingOffer.proto\"Y\n\x0fSignalingGetLog\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12%\n\npagination\x18\x02 \x01(\x0b\x32\x11.proto.Pagination\"\x96\x03\n\x17SignalingGetLogResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x42\n\rsignaling_log\x18\x02 \x03(\x0b\x32+.proto.SignalingGetLogResponse.SignalingLog\x1a\x93\x02\n\x0cSignalingLog\x12\n\n\x02id\x18\x01 \x01(\x04\x12(\n\x04type\x18\x02 \x01(\x0e\x32\x1a.proto.SignalingOffer.Type\x12\x42\n\x06status\x18\x03 \x01(\x0e\x32\x32.proto.SignalingGetLogResponse.SignalingLog.Status\x12#\n\x04peer\x18\x04 \x01(\x0b\x32\x15.proto.RegisteredUser\x12\x12\n\noffer_time\x18\x05 \x01(\r\x12\x10\n\x08\x64uration\x18\x06 \x01(\r\">\n\x06Status\x12\n\n\x06MISSED\x10\x00\x12\x0c\n\x08\x43\x41NCELED\x10\x01\x12\x0c\n\x08INCOMING\x10\x02\x12\x0c\n\x08OUTGOING\x10\x03\x42&\n\x0enet.iGap.protoB\x14ProtoSignalingGetLogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignalingGetLog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\024ProtoSignalingGetLog'
  _globals['_SIGNALINGGETLOG']._serialized_start=99
  _globals['_SIGNALINGGETLOG']._serialized_end=188
  _globals['_SIGNALINGGETLOGRESPONSE']._serialized_start=191
  _globals['_SIGNALINGGETLOGRESPONSE']._serialized_end=597
  _globals['_SIGNALINGGETLOGRESPONSE_SIGNALINGLOG']._serialized_start=322
  _globals['_SIGNALINGGETLOGRESPONSE_SIGNALINGLOG']._serialized_end=597
  _globals['_SIGNALINGGETLOGRESPONSE_SIGNALINGLOG_STATUS']._serialized_start=535
  _globals['_SIGNALINGGETLOGRESPONSE_SIGNALINGLOG_STATUS']._serialized_end=597
# @@protoc_insertion_point(module_scope)
