# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignalingGetConfiguration.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'SignalingGetConfiguration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fSignalingGetConfiguration.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"<\n\x19SignalingGetConfiguration\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xa9\x02\n!SignalingGetConfigurationResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x46\n\nice_server\x18\x02 \x03(\x0b\x32\x32.proto.SignalingGetConfigurationResponse.IceServer\x12\x15\n\rvoice_calling\x18\x03 \x01(\x08\x12\x15\n\rvideo_calling\x18\x04 \x01(\x08\x12\x16\n\x0escreen_sharing\x18\x05 \x01(\x08\x12\x13\n\x0bsecret_chat\x18\x06 \x01(\x08\x1a>\n\tIceServer\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x12\n\ncredential\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\tB0\n\x0enet.iGap.protoB\x1eProtoSignalingGetConfigurationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignalingGetConfiguration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\036ProtoSignalingGetConfiguration'
  _globals['_SIGNALINGGETCONFIGURATION']._serialized_start=73
  _globals['_SIGNALINGGETCONFIGURATION']._serialized_end=133
  _globals['_SIGNALINGGETCONFIGURATIONRESPONSE']._serialized_start=136
  _globals['_SIGNALINGGETCONFIGURATIONRESPONSE']._serialized_end=433
  _globals['_SIGNALINGGETCONFIGURATIONRESPONSE_ICESERVER']._serialized_start=371
  _globals['_SIGNALINGGETCONFIGURATIONRESPONSE_ICESERVER']._serialized_end=433
# @@protoc_insertion_point(module_scope)
