# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SignalingLeave.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'SignalingLeave.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SignalingLeave.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"1\n\x0eSignalingLeave\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xee\x01\n\x16SignalingLeaveResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".proto.SignalingLeaveResponse.Type\"\x7f\n\x04Type\x12\n\n\x06MISSED\x10\x00\x12\x0c\n\x08REJECTED\x10\x01\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x02\x12\x10\n\x0cNOT_ANSWERED\x10\x03\x12\x0f\n\x0bUNAVAILABLE\x10\x04\x12\x10\n\x0c\x44ISCONNECTED\x10\x05\x12\x0c\n\x08\x46INISHED\x10\x06\x12\x0c\n\x08TOO_LONG\x10\x07\x42%\n\x0enet.iGap.protoB\x13ProtoSignalingLeaveb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignalingLeave_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\023ProtoSignalingLeave'
  _globals['_SIGNALINGLEAVE']._serialized_start=62
  _globals['_SIGNALINGLEAVE']._serialized_end=111
  _globals['_SIGNALINGLEAVERESPONSE']._serialized_start=114
  _globals['_SIGNALINGLEAVERESPONSE']._serialized_end=352
  _globals['_SIGNALINGLEAVERESPONSE_TYPE']._serialized_start=225
  _globals['_SIGNALINGLEAVERESPONSE_TYPE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
