# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserTwoStepVerificationChangeRecoveryQuestion.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserTwoStepVerificationChangeRecoveryQuestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3UserTwoStepVerificationChangeRecoveryQuestion.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xb6\x01\n-UserTwoStepVerificationChangeRecoveryQuestion\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x14\n\x0cquestion_one\x18\x03 \x01(\t\x12\x12\n\nanswer_one\x18\x04 \x01(\t\x12\x14\n\x0cquestion_two\x18\x05 \x01(\t\x12\x12\n\nanswer_two\x18\x06 \x01(\t\"Z\n5UserTwoStepVerificationChangeRecoveryQuestionResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.ResponseBD\n\x0enet.iGap.protoB2ProtoUserTwoStepVerificationChangeRecoveryQuestionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserTwoStepVerificationChangeRecoveryQuestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB2ProtoUserTwoStepVerificationChangeRecoveryQuestion'
  _globals['_USERTWOSTEPVERIFICATIONCHANGERECOVERYQUESTION']._serialized_start=94
  _globals['_USERTWOSTEPVERIFICATIONCHANGERECOVERYQUESTION']._serialized_end=276
  _globals['_USERTWOSTEPVERIFICATIONCHANGERECOVERYQUESTIONRESPONSE']._serialized_start=278
  _globals['_USERTWOSTEPVERIFICATIONCHANGERECOVERYQUESTIONRESPONSE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
