# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserContactsImport.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserContactsImport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18UserContactsImport.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xcd\x01\n\x12UserContactsImport\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x33\n\x08\x63ontacts\x18\x02 \x03(\x0b\x32!.proto.UserContactsImport.Contact\x12\r\n\x05\x66orce\x18\x03 \x01(\x08\x1aR\n\x07\x43ontact\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"\xb6\x01\n\x1aUserContactsImportResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x46\n\x13registered_contacts\x18\x02 \x03(\x0b\x32).proto.UserContactsImportResponse.Contact\x1a-\n\x07\x43ontact\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x42)\n\x0enet.iGap.protoB\x17ProtoUserContactsImportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserContactsImport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\027ProtoUserContactsImport'
  _globals['_USERCONTACTSIMPORT']._serialized_start=67
  _globals['_USERCONTACTSIMPORT']._serialized_end=272
  _globals['_USERCONTACTSIMPORT_CONTACT']._serialized_start=190
  _globals['_USERCONTACTSIMPORT_CONTACT']._serialized_end=272
  _globals['_USERCONTACTSIMPORTRESPONSE']._serialized_start=275
  _globals['_USERCONTACTSIMPORTRESPONSE']._serialized_end=457
  _globals['_USERCONTACTSIMPORTRESPONSE_CONTACT']._serialized_start=412
  _globals['_USERCONTACTSIMPORTRESPONSE_CONTACT']._serialized_end=457
# @@protoc_insertion_point(module_scope)
