# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserSessionGetActiveList.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserSessionGetActiveList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eUserSessionGetActiveList.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\";\n\x18UserSessionGetActiveList\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xe5\x03\n UserSessionGetActiveListResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12@\n\x07session\x18\x02 \x03(\x0b\x32/.proto.UserSessionGetActiveListResponse.Session\x1a\xdb\x02\n\x07Session\x12\x12\n\nsession_id\x18\x01 \x01(\x04\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x03 \x01(\r\x12\x19\n\x11\x61pp_build_version\x18\x04 \x01(\r\x12\x13\n\x0b\x61pp_version\x18\x05 \x01(\t\x12!\n\x08platform\x18\x06 \x01(\x0e\x32\x0f.proto.Platform\x12\x18\n\x10platform_version\x18\x07 \x01(\t\x12\x1d\n\x06\x64\x65vice\x18\x08 \x01(\x0e\x32\r.proto.Device\x12\x13\n\x0b\x64\x65vice_name\x18\t \x01(\t\x12!\n\x08language\x18\n \x01(\x0e\x32\x0f.proto.Language\x12\x0f\n\x07\x63ountry\x18\x0b \x01(\t\x12\x0f\n\x07\x63urrent\x18\x0c \x01(\x08\x12\x13\n\x0b\x63reate_time\x18\r \x01(\r\x12\x13\n\x0b\x61\x63tive_time\x18\x0e \x01(\r\x12\n\n\x02ip\x18\x0f \x01(\tB/\n\x0enet.iGap.protoB\x1dProtoUserSessionGetActiveListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserSessionGetActiveList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\035ProtoUserSessionGetActiveList'
  _globals['_USERSESSIONGETACTIVELIST']._serialized_start=86
  _globals['_USERSESSIONGETACTIVELIST']._serialized_end=145
  _globals['_USERSESSIONGETACTIVELISTRESPONSE']._serialized_start=148
  _globals['_USERSESSIONGETACTIVELISTRESPONSE']._serialized_end=633
  _globals['_USERSESSIONGETACTIVELISTRESPONSE_SESSION']._serialized_start=286
  _globals['_USERSESSIONGETACTIVELISTRESPONSE_SESSION']._serialized_end=633
# @@protoc_insertion_point(module_scope)
