# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserLogin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserLogin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fUserLogin.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"\xa1\x02\n\tUserLogin\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x03 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x04 \x01(\r\x12\x19\n\x11\x61pp_build_version\x18\x05 \x01(\r\x12\x13\n\x0b\x61pp_version\x18\x06 \x01(\t\x12!\n\x08platform\x18\x07 \x01(\x0e\x32\x0f.proto.Platform\x12\x18\n\x10platform_version\x18\x08 \x01(\t\x12\x1d\n\x06\x64\x65vice\x18\t \x01(\x0e\x32\r.proto.Device\x12\x13\n\x0b\x64\x65vice_name\x18\n \x01(\t\x12!\n\x08language\x18\x0b \x01(\x0e\x32\x0f.proto.Language\"\x83\x02\n\x11UserLoginResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x19\n\x11\x64\x65precated_client\x18\x02 \x01(\x08\x12\x1b\n\x13secondary_node_name\x18\x03 \x01(\t\x12\x18\n\x10update_available\x18\x04 \x01(\x08\x12+\n#chat_delete_message_for_both_period\x18\x05 \x01(\r\x12\x15\n\rwallet_active\x18\x06 \x01(\x08\x12\x12\n\nmpl_active\x18\x07 \x01(\x08\x12!\n\x19wallet_agreement_accepted\x18\x08 \x01(\x08\x42 \n\x0enet.iGap.protoB\x0eProtoUserLoginb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserLogin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\016ProtoUserLogin'
  _globals['_USERLOGIN']._serialized_start=72
  _globals['_USERLOGIN']._serialized_end=361
  _globals['_USERLOGINRESPONSE']._serialized_start=364
  _globals['_USERLOGINRESPONSE']._serialized_end=623
# @@protoc_insertion_point(module_scope)
