# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserProfileGetBio.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserProfileGetBio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17UserProfileGetBio.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"4\n\x11UserProfileGetBio\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"K\n\x19UserProfileGetBioResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x0b\n\x03\x62io\x18\x02 \x01(\tB(\n\x0enet.iGap.protoB\x16ProtoUserProfileGetBiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserProfileGetBio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\026ProtoUserProfileGetBio'
  _globals['_USERPROFILEGETBIO']._serialized_start=65
  _globals['_USERPROFILEGETBIO']._serialized_end=117
  _globals['_USERPROFILEGETBIORESPONSE']._serialized_start=119
  _globals['_USERPROFILEGETBIORESPONSE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
