# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserTwoStepVerificationGetPasswordDetail.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserTwoStepVerificationGetPasswordDetail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.UserTwoStepVerificationGetPasswordDetail.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"K\n(UserTwoStepVerificationGetPasswordDetail\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xd8\x01\n0UserTwoStepVerificationGetPasswordDetailResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x14\n\x0cquestion_one\x18\x02 \x01(\t\x12\x14\n\x0cquestion_two\x18\x03 \x01(\t\x12\x0c\n\x04hint\x18\x04 \x01(\t\x12$\n\x1chas_confirmed_recovery_email\x18\x05 \x01(\x08\x12!\n\x19unconfirmed_email_pattern\x18\x06 \x01(\tB?\n\x0enet.iGap.protoB-ProtoUserTwoStepVerificationGetPasswordDetailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserTwoStepVerificationGetPasswordDetail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB-ProtoUserTwoStepVerificationGetPasswordDetail'
  _globals['_USERTWOSTEPVERIFICATIONGETPASSWORDDETAIL']._serialized_start=88
  _globals['_USERTWOSTEPVERIFICATIONGETPASSWORDDETAIL']._serialized_end=163
  _globals['_USERTWOSTEPVERIFICATIONGETPASSWORDDETAILRESPONSE']._serialized_start=166
  _globals['_USERTWOSTEPVERIFICATIONGETPASSWORDDETAILRESPONSE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
