# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserContactsGetList.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserContactsGetList.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2
import Global_pb2 as Global__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19UserContactsGetList.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\x1a\x0cGlobal.proto\"6\n\x13UserContactsGetList\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"p\n\x1bUserContactsGetListResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12.\n\x0fregistered_user\x18\x02 \x03(\x0b\x32\x15.proto.RegisteredUserB*\n\x0enet.iGap.protoB\x18ProtoUserContactsGetListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserContactsGetList_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\030ProtoUserContactsGetList'
  _globals['_USERCONTACTSGETLIST']._serialized_start=81
  _globals['_USERCONTACTSGETLIST']._serialized_end=135
  _globals['_USERCONTACTSGETLISTRESPONSE']._serialized_start=137
  _globals['_USERCONTACTSGETLISTRESPONSE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
