# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserRegister.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserRegister.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12UserRegister.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xf1\x01\n\x0cUserRegister\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x14\n\x0cphone_number\x18\x02 \x01(\x04\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\x12?\n\x11preference_method\x18\x04 \x01(\x0e\x32$.proto.UserRegister.PreferenceMethod\"S\n\x10PreferenceMethod\x12\x14\n\x10VERIFY_CODE_AUTO\x10\x00\x12\x13\n\x0fVERIFY_CODE_SMS\x10\x01\x12\x14\n\x10VERIFY_CODE_CALL\x10\x02\"\x93\x03\n\x14UserRegisterResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x04\x12\x13\n\x0b\x61uthor_hash\x18\x04 \x01(\t\x12\x32\n\x06method\x18\x05 \x01(\x0e\x32\".proto.UserRegisterResponse.Method\x12\x14\n\x0cresend_delay\x18\x06 \x01(\r\x12\x12\n\nsms_number\x18\x07 \x03(\x04\x12\x19\n\x11verify_code_regex\x18\x08 \x01(\t\x12\x1f\n\x17verify_code_digit_count\x18\t \x01(\r\x12\x1d\n\x15\x63\x61ll_method_supported\x18\n \x01(\x08\"g\n\x06Method\x12\x13\n\x0fVERIFY_CODE_SMS\x10\x00\x12\x16\n\x12VERIFY_CODE_SOCKET\x10\x01\x12\x1a\n\x16VERIFY_CODE_SMS_SOCKET\x10\x02\x12\x14\n\x10VERIFY_CODE_CALL\x10\x03\x42#\n\x0enet.iGap.protoB\x11ProtoUserRegisterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserRegister_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\021ProtoUserRegister'
  _globals['_USERREGISTER']._serialized_start=61
  _globals['_USERREGISTER']._serialized_end=302
  _globals['_USERREGISTER_PREFERENCEMETHOD']._serialized_start=219
  _globals['_USERREGISTER_PREFERENCEMETHOD']._serialized_end=302
  _globals['_USERREGISTERRESPONSE']._serialized_start=305
  _globals['_USERREGISTERRESPONSE']._serialized_end=708
  _globals['_USERREGISTERRESPONSE_METHOD']._serialized_start=605
  _globals['_USERREGISTERRESPONSE_METHOD']._serialized_end=708
# @@protoc_insertion_point(module_scope)
