# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: UserReport.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'UserReport.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10UserReport.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"\xb9\x01\n\nUserReport\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\x12\x0f\n\x07user_id\x18\x02 \x01(\x04\x12(\n\x06reason\x18\x03 \x01(\x0e\x32\x18.proto.UserReport.Reason\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\":\n\x06Reason\x12\t\n\x05OTHER\x10\x00\x12\x08\n\x04SPAM\x10\x01\x12\t\n\x05\x41\x42USE\x10\x02\x12\x10\n\x0c\x46\x41KE_ACCOUNT\x10\x03\"7\n\x12UserReportResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.ResponseB!\n\x0enet.iGap.protoB\x0fProtoUserReportb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'UserReport_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\017ProtoUserReport'
  _globals['_USERREPORT']._serialized_start=59
  _globals['_USERREPORT']._serialized_end=244
  _globals['_USERREPORT_REASON']._serialized_start=186
  _globals['_USERREPORT_REASON']._serialized_end=244
  _globals['_USERREPORTRESPONSE']._serialized_start=246
  _globals['_USERREPORTRESPONSE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
