# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WalletGetAccessToken.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'WalletGetAccessToken.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Request_pb2 as Request__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aWalletGetAccessToken.proto\x12\x05proto\x1a\rRequest.proto\x1a\x0eResponse.proto\"7\n\x14WalletGetAccessToken\x12\x1f\n\x07request\x18\x01 \x01(\x0b\x32\x0e.proto.Request\"\xc7\x01\n\x1cWalletGetAccessTokenResponse\x12!\n\x08response\x18\x01 \x01(\x0b\x32\x0f.proto.Response\x12\x41\n\ntoken_type\x18\x02 \x01(\x0e\x32-.proto.WalletGetAccessTokenResponse.TokenType\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x12\n\nexpires_in\x18\x04 \x01(\r\"\x17\n\tTokenType\x12\n\n\x06\x42\x45\x41RER\x10\x00\x42+\n\x0enet.iGap.protoB\x19ProtoWalletGetAccessTokenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WalletGetAccessToken_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016net.iGap.protoB\031ProtoWalletGetAccessToken'
  _globals['_WALLETGETACCESSTOKEN']._serialized_start=68
  _globals['_WALLETGETACCESSTOKEN']._serialized_end=123
  _globals['_WALLETGETACCESSTOKENRESPONSE']._serialized_start=126
  _globals['_WALLETGETACCESSTOKENRESPONSE']._serialized_end=325
  _globals['_WALLETGETACCESSTOKENRESPONSE_TOKENTYPE']._serialized_start=302
  _globals['_WALLETGETACCESSTOKENRESPONSE_TOKENTYPE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
